### ISSUE TITLE
Grillbout.cloud 

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#17]
When opening audit log on grillbot.cloud this error message pops up. No audits are shown.
![image](https://user-images.githubusercontent.com/56552845/212140777-2bc92bb4-6052-4e32-a484-56eb402cbbf2.png)

**Comment by solumath** [comment]
same problem with tab invites
![image](https://user-images.githubusercontent.com/56552845/212142756-f3923111-12a9-43d8-b2ce-0a9b890ed559.png)

**Comment by Misha12** [comment]
You have very old incompatible filter stored in the local storage. Try clear filter.
