### ISSUE TITLE
Log channel position change

### ISSUE THREAD

**Issue by Toaster192** [GrillBot/grillbot#3]
Since recently we've had incidents where a lot of the channels moved to seemingly random places (but since they seem to have moved to the same place both times it seems like some sort of discord bug bullshit, w/e) it'd be nice to have these movements logged so we can better understand what's causing it or have more details to provide once we inevitably bother the ever helpful discord support with this.

**Comment by Misha12** [comment]
Implemented in `events-refactor` (https://github.com/GrillBot/grillbot/pull/2) branch and deployed in production. The bot will store data and in the future a presentation in the web administration will be added.
