### ISSUE TITLE
Channel snapshots

### ISSUE THREAD

**Issue by Misha12** [GrillBot/grillbot#6]
Instead of current logging of channel position change implement new feature that create snapshot of channels in the guild.
This feature creates snapshots of guild channels when event `ChannelUpdated` was fired and every 12 hours. 
This snapshots will be stored in the database table and accessible in web administration via private API.

**Comment by Toaster192** [comment]
Hopefully not as needed now that you can't drag and drop channels by default. We still have a single "snapshot" via the Server Template discord feature.
