### ISSUE TITLE
command `/solve` wrong operation order

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#73]
if i give `/solve 2+1/(1/0)` the given result is 2. Which is wrong. Seems like it doesn't support brackets.

**Comment by Misha12** [comment]
Parentheses support exists, but javascript (Math.JS API uses javascript evaluation) will evaluate the expression part `(1/0)` as `Infinity` and `2+1/Infinity` will be evaluated as `2`. The solution might be to parse the expression and detect division by zero and return an error, but the Math.JS API doesn't support expression parsing, but the Math.JS library (supplied as an NPM package) does. This means that a service would need to be created that implements the Math.JS library and implements division-by-zero detection. But using the `/solve` command is not enough to make the implementation worthwhile.
