### ISSUE TITLE
/admin clean_messages not removing

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#77]
`/admin clean_messages` doesnt remove older messages. Seems like it depends on cache or stored messages in bot.

**Comment by Misha12** [comment]
I've deployed a new version to production that deletes messages from the message cache and from discord one by one instead of deleting them in bulk via single API request. The deletion of ephemeral messages has also been fixed.

**Comment by solumath** [comment]
It is now working properly, thank you for the fix!
