### ISSUE TITLE
discord timestamp in /duck

### ISSUE THREAD

**Issue by solumath** [GrillBot/grillbot#85]
I think it would be better to use relative timestamp to show events coming up. For example here in `/duck` command.
![image](https://github.com/GrillBot/grillbot/assets/56552845/855bb415-978c-4ce5-9df9-982ad4b1e99d)

**Comment by Misha12** [comment]
Currently frozen until I get information from the KachnaOnline developers that the datetimes returned from the API are UTC or local time (the API does not return timezone information). Probably current command implementation contains a bug. Needs more investigation. It might be frozen until KachnaOnline changes the serialization and the API starts returning timezone information.
